x-global-environment: &global
  env_file:
    - envs/.env # env file - NOT committed to Git

services:
  # Caddy reverse proxy - web-facing SSL server
  caddy:
    <<: *global # this will inherit all the envs from x-global-environment
    depends_on:
      - django
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - npda-caddy-data:/data/
      - npda-caddy-data:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticdocs:/srv/staticdocs

  # Django web application
  django: &django
    <<: *global # this will inherit all the envs from x-global-environment
    build: .
    image: npda-django:built # build image and save for use by other containers
    depends_on:
      - postgis
      - redis
    volumes:
      - .:/app/
    command: s/start-dev
    restart: always

  # Redis backend for Celery task scheduler
  redis:
    image: redis:alpine
    expose:
      - 6379
    restart: always

  # Celery worker
  celeryworker:
    <<: *global # this will inherit config from x-global-environment
    image: npda-django:built
    command: celery -A project.npda worker -l info
    restart: always

  # Flower UI for Celery tasks
  flower:
    <<: *global # this will inherit config from x-global-environment
    image: npda-django:built
    ports:
      - 8888:8888
    volumes:
      - npda-flower-data:/data
    command: celery -A project.npda flower --persistent=True -url_prefix=/flower
    restart: always
    depends_on:
      - redis
      - django

  # Celery scheduled tasks/cron
  celerybeat:
    <<: *global # this will inherit config from x-global-environment
    image: npda-django:built
    command: celery -A project.npda beat -l info
    restart: always

  # PostgreSQL with PostGIS extension
  postgis:
    <<: *global # this will inherit all the envs from x-global-environment
    image: postgis/postgis:15-3.3
    volumes:
      - npda-postgis-data:/var/lib/postgresql/data
    restart: always

  mkdocs:
    <<: *django # this will inherit all the settings from the django service
    ports:
      - 8007:8007
    command: >
      sh -c "mkdocs build --config-file documentation/mkdocs.yml &&
        mkdocs serve --config-file documentation/mkdocs.yml"
    restart: always

volumes:
  npda-caddy-data:
  npda-postgis-data:
  npda-flower-data:
