x-global-environment: &global
  env_file:
    - envs/.env # env file - NOT committed to Git

services:
  # Caddy reverse proxy - web-facing SSL server
  caddy:
    <<: *global # this will inherit all the envs from x-global-environment
    depends_on:
      - django
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - npda-caddy-data:/data/
      - npda-caddy-data:/config/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./staticdocs:/srv/staticdocs

  # Django web application
  django: &django
    <<: *global # this will inherit all the envs from x-global-environment
    build: .
    image: npda-django:built # build image and save for use by other containers
    depends_on:
      - postgis
    volumes:
      - .:/app/
    command: s/start-dev
    restart: always

  # PostgreSQL with PostGIS extension
  postgis:
    <<: *global # this will inherit all the envs from x-global-environment
    image: postgis/postgis:15-3.3
    volumes:
      - npda-postgis-data:/var/lib/postgresql/data
    restart: always

  mkdocs:
    <<: *django # this will inherit all the settings from the django service
    ports:
      - 8007:8007
    command: >
      sh -c "mkdocs build --config-file documentation/mkdocs.yml &&
        mkdocs serve --config-file documentation/mkdocs.yml"
    restart: always
  
  # E2E tests with Playwright so we don't need to install browsers in the main app container
  e2e:
    <<: *global # this will inherit all the envs from x-global-environment
    build:
      dockerfile_inline: |
        FROM npda-django:built
        RUN playwright install --with-deps chromium
    depends_on:
      - django
    volumes:
      - .:/app/
    command: >
      sh -c "PWDEBUG=1 pytest -s"
    

volumes:
  npda-caddy-data:
  npda-postgis-data:
