# Generated by Django 5.1.3 on 2024-11-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0015_alter_patientsubmission_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="csv_file",
            field=models.FileField(
                help_text="CSV file containing the audit data for this submission",
                null=True,
                upload_to="submissions/csv/",
            ),
        ),
    ]
