# Generated by Django 5.1.3 on 2024-11-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0016_alter_submission_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="errors",
            field=models.JSONField(
                blank=True,
                help_text="Errors that have been found in the uploaded CSV file",
                null=True,
                verbose_name="Errors",
            ),
        ),
    ]
