# Generated by Django 5.1.2 on 2024-11-12 21:50

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0017_submission_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="weight",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "Patient Weight (kg)",
                    "reference": "By providing ALL measurements of HbA1c a more powerful data analysis can be performed centrally. Allows means/median values for the year to be calculated. Data from first 3 months following diagnosis should be supplied but will be analysed independently as early measurements of HbA1c are not representative of overall diabetes control. NG18: 1 1.2.71 Offer children and young people with type 1 diabetes measurement of their HbA1c level 4 times a year (more frequent testing may be appropriate if there is concern about suboptimal blood glucose control). NG18: 1.3.28 Measure HbA1c levels every 3 months in children and young people with type 2 diabetes.",
                },
                max_digits=4,
                null=True,
                verbose_name="Patient Weight (kg)",
            ),
        ),
    ]
