# Generated by Django 5.1.3 on 2024-11-15 18:32

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0018_alter_visit_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="bmi",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. BMI value for the patient.",
                    "reference": "The BMI is calculated using the height and weight of the patient. This is used to calculate the body mass index sds and centile of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="bmi_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. Centile value for height if available. If not available, can be blank.",
                    "reference": "Using the UK-WHO growth charts, the centile value for height is calculated based on the height in cm and age of the patient. This is used to assess the growth of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index Centile",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="bmi_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. Centile value for body mass index if height and weight are available. If not available, can be blank.",
                    "reference": "Using the UK-WHO growth charts, the sds value for body mass index is calculated based on the body mass index in kg/m² and age of the patient. This is used to assess the growth of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Body Mass Index SDS",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="height_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. Centile value for height if available. If not available, can be blank.",
                    "reference": "Using the UK-WHO growth charts, the centile value for height is calculated based on the height in cm and age of the patient. This is used to assess the growth of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Height Centile",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="height_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. Centile value for height if available. If not available, can be blank.",
                    "reference": "Using the UK-WHO growth charts, the sds value for height is calculated based on the height in cm and age of the patient. This is used to assess the growth of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Height SDS",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="weight_centile",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. Centile value for weight if available. If not available, can be blank.",
                    "reference": "Using the UK-WHO growth charts, the centile value for weight is calculated based on the weight in kg and age of the patient. This is used to assess the growth of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Weight Centile",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="weight_sds",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "This is a calculated field. Centile value for weight if available. If not available, can be blank.",
                    "reference": "Using the UK-WHO growth charts, the sds value for weight is calculated based on the weight in kg and age of the patient. This is used to assess the growth of the patient.",
                },
                max_digits=3,
                null=True,
                verbose_name="Weight SDS",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="weight",
            field=project.npda.models.categorised_formfield_mixin.CategorisedDecimalField(
                blank=True,
                decimal_places=1,
                default=None,
                help_text={
                    "label": "Patient Weight (kg)",
                    "reference": "NG18: 1.2.45 At each clinic visit for children and young people with type 1 diabetes measure height and weight and plot on an appropriate growth chart. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015], NG18: 1.3.20 At each clinic visit for children and young people with type 2 diabetes: • measure height and weight and plot on an appropriate growth chart • calculate BMI. Check for normal growth and/or significant changes in weight because these may reflect changes in blood glucose control. [2004, amended 2015]",
                },
                max_digits=4,
                null=True,
                verbose_name="Patient Weight (kg)",
            ),
        ),
    ]
