# Generated by Django 5.1.3 on 2024-12-01 21:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0019_visit_bmi_visit_bmi_centile_visit_bmi_sds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="location_bng",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as British National Grid (BNG)",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="location_wgs",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as British National Grid (BNG)",
                null=True,
                srid=27700,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="location_wgs84",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="longitude and latitude of the postcode as WGS 84",
                null=True,
                srid=4326,
            ),
        ),
    ]
