# Generated by Django 5.1.4 on 2025-01-15 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0020_patient_location_bng_patient_location_wgs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="previous_pz_code",
        ),
    ]
