# Generated by Django 5.1.4 on 2025-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0020_patient_location_bng_patient_location_wgs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="csv_file",
            field=models.BinaryField(
                help_text="CSV file containing the audit data for this submission",
                null=True,
            ),
        ),
    ]
