# Generated by Django 5.1.5 on 2025-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0020_patient_location_bng_patient_location_wgs_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
