# Generated by Django 5.1.5 on 2025-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0020_patient_location_bng_patient_location_wgs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="csv_file_name",
            field=models.CharField(
                help_text="Name of the uploaded CSV file",
                null=True,
                verbose_name="CSV file name",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="csv_file",
            field=models.BinaryField(
                help_text="CSV file containing the audit data for this submission",
                null=True,
            ),
        ),
    ]
