# Generated by Django 5.1.4 on 2025-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0021_alter_submission_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="csv_file_name",
            field=models.CharField(
                help_text="Name of the uploaded CSV file",
                null=True,
                verbose_name="CSV file name",
            ),
        ),
    ]
