# Generated by Django 5.1.5 on 2025-01-24 21:22

import project.npda.models.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0021_submission_csv_file_name_alter_submission_csv_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "ordering": ("pk", "nhs_number", "unique_reference_number"),
                "permissions": [
                    (
                        "can_lock_child_patient_data_from_editing",
                        "Can lock a child's record from editing.",
                    ),
                    (
                        "can_unlock_child_patient_data_from_editing",
                        "Can unlock a child's record from editing.",
                    ),
                    (
                        "can_opt_out_child_from_inclusion_in_audit",
                        "Can sanction an opt out from participating in the audit. Note all the child's date except NPDA unique identifier are irretrievably deleted.",
                    ),
                ],
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="unique_reference_number",
            field=models.CharField(
                blank=True,
                help_text="This is the NHS number for England and Wales. It is used to identify the patient in the audit.",
                max_length=50,
                null=True,
                verbose_name="Unique Reference Number",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nhs_number",
            field=models.CharField(
                blank=True,
                help_text="This is a unique reference number for Jersey patients. It is used to identify the patient in the audit.",
                null=True,
                validators=[project.npda.models.custom_validators.validate_nhs_number],
                verbose_name="NHS Number",
            ),
        ),
    ]
