# Generated by Django 5.1.5 on 2025-01-26 09:12

import project.npda.models.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0023_alter_patient_nhs_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="unique_reference_number",
            field=models.CharField(
                blank=True,
                help_text="This is a unique reference number for Jersey patients. It is used to identify the patient in the audit.",
                max_length=50,
                null=True,
                validators=[
                    project.npda.models.custom_validators.validate_unique_reference_number
                ],
                verbose_name="Unique Reference Number",
            ),
        ),
    ]
