# Generated by Django 5.1.5 on 2025-02-09 23:02

import project.npda.models.categorised_formfield_mixin
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("npda", "0024_alter_patient_unique_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="hospital_admission_reason",
            field=project.npda.models.categorised_formfield_mixin.CategorisedPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Stabilisation of Diabetes"),
                    (2, "DKA"),
                    (3, "Ketosis without Acidosis"),
                    (4, "Hypoglycaemia"),
                    (5, "Surgical Procedures"),
                    (6, "Other causes"),
                ],
                default=None,
                help_text={
                    "label": "Use option 1: Stabilisation of diabetes for new patients admitted without DKA or other admissions where the purpose was to stabilise blood glucose such as recurrent hyperglycaemia without acidosis.",
                    "reference": "Important to know why a child is admitted to hospital for reasons of having diabetes but not related to DKA or hypoglycaemia. Also to record incidence of DKA and hypoglycaemia complications. With Best Practice Tariff it is envisaged that this type of admission will decrease and this is of interest to commissioners. Please only record diabetes-related admissions.",
                },
                null=True,
                verbose_name="Reason for admission",
            ),
        ),
    ]
