#!/bin/bash -e

ENVIRONMENT=local

while [[ $# -gt 0 ]]; do
    case ${1} in
        --environment)
            ENVIRONMENT="${2}"
            shift # past argument
            shift # past value
        ;;
        -*|--*)
            echo "Unknown option ${1}"
            exit 1
            ;;
  esac
done

function connect_to_azure_db() {
    local host="npda-$1.postgres.database.azure.com"
    local user="$3"
    local dbname="$2"
    
    local access_token=$(az account get-access-token --resource-type oss-rdbms --query 'accessToken' --output tsv)

    PGPASSWORD="${access_token}" psql "host=${host} user=${user} dbname=${dbname} sslmode=require"
}

case ${ENVIRONMENT} in
    'local')
        docker compose exec postgis psql -U npdauser -d npdadb
        ;;

    'staging')
        connect_to_azure_db 'staging' 'npda_staging' "NPDA\ Database\ Owners"
        ;;
    
    'live')
        connect_to_azure_db 'live' 'npda_live' "NPDA\ Live\ Database\ Owners"
        ;;

    *)
        echo "Unknown environment ${ENVIRONMENT} - expected local, staging or live"
esac