#!/bin/bash -e

az login --identity

az storage file download \
    --auth-mode login \
    --enable-file-backup-request-intent \
    --account-name ${AZURE_CONFIG_STORAGE_ACCOUNT} \
    --share-name ${AZURE_CONFIG_FILE_SHARE} \
    --path .env --dest envs/.env

python manage.py write_azure_pg_password_file
python manage.py makemigrations
python manage.py migrate
python manage.py seed --mode=seed_groups_and_permissions

gunicorn \
    --bind=0.0.0.0:8000 \
    --timeout 600 \
    --access-logfile '-' \
    --access-logformat '%({x-forwarded-for}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"' \
    project.wsgi