#!/bin/bash
# Runs the tailwind watch command in the running django container
export PROJECT_NAME="national-paediatric-diabetes-audit"
export DJANGO_SERVICE_NAME="django"
CONTAINER_NAME="${PROJECT_NAME}-${DJANGO_SERVICE_NAME}-1"

# Ensure the container is running
if ! docker ps --format "{{.Names}}" | grep "^$CONTAINER_NAME\$"; then
    echo "Error: Container '$CONTAINER_NAME' is not running. Exiting."
    echo "Running containers:"
    docker ps
    exit 1
fi

green_echo() {
    echo -e "\033[32m$1\033[0m"
}

green_echo "Running tailwind watch in container '${CONTAINER_NAME}'..."

docker exec -it $CONTAINER_NAME bash -c "npm run watch:css"