# Runs the PR check script
# The workflow is named pytest.yml to maintain history in GitHub actions

name: Run PR checks

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-run-pytest-suite-in-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full code repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to allow git_context_processor.py to still work

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run PR check script'
        env:
          AZURE_CONFIG_STORAGE_ACCOUNT: ${{ secrets.AZURE_CONFIG_STORAGE_ACCOUNT }}
          AZURE_CONFIG_FILE_SHARE: ${{ secrets.AZURE_CONFIG_FILE_SHARE }}
        run: s/pr-check
